user ====> {
  "uid":"t9BZZRFpgNTCpK2o1PCF5wnJARr1",
  "displayName":null,
  "photoURL":null,
  "email":"mile@hotmail.com",
  "emailVerified":false,
  "phoneNumber":null,
  "isAnonymous":false,
  "tenantId":null,
  "providerData":[
    {"uid":"mile@hotmail.com",
    "displayName":null,
    "photoURL":null,
    "email":"mile@hotmail.com",
    "phoneNumber":null,
    "providerId":"password"
  }],
  "apiKey":"AIzaSyCcosYVhMJ5LriT-F_s3YgWeB_qM9_P6u0",
  "appName":"[DEFAULT]",
  "authDomain":"app-urgencias-oftamologicas.firebaseapp.com",
  "stsTokenManager":
    {"apiKey":"AIzaSyCcosYVhMJ5LriT-F_s3YgWeB_qM9_P6u0",
      "refreshToken":"AGEhc0DygyeD6DWtEDOknSKfNcYx9dpp4vxKWR2p_YveLC-KvKKlQELWj95VkphG0Kc5yceTd5RSk358v1kGCFQggdJk60JR2NNhphKqOvoKBDQbGwNw9zsUQs-GSM4dGW-wdz2-4qvW8Gqz_U9ttf9VPispYu8Eer5vRgw8-8hvrJnV_YUoZFUoxmUmmipLdySfWQH8rTJVTOCWQhkBMp5-SrZiQzgBmSnR5dHc2XCnCJ2IUQAdJNI",
      "accessToken":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjUzNmRhZWFiZjhkZDY1ZDRkZTIxZTgyNGI4OTlhMWYzZGEyZjg5NTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBwLXVyZ2VuY2lhcy1vZnRhbW9sb2dpY2FzIiwiYXVkIjoiYXBwLXVyZ2VuY2lhcy1vZnRhbW9sb2dpY2FzIiwiYXV0aF90aW1lIjoxNjIxMjIxNjY3LCJ1c2VyX2lkIjoidDlCWlpSRnBnTlRDcEsybzFQQ0Y1d25KQVJyMSIsInN1YiI6InQ5QlpaUkZwZ05UQ3BLMm8xUENGNXduSkFScjEiLCJpYXQiOjE2MjEyMjE2NjcsImV4cCI6MTYyMTIyNTI2NywiZW1haWwiOiJtaWxlQGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1pbGVAaG90bWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.E96AKLxGXowBN1gTVXfIFSMfipMKuUo-jPoiMwfgUWO85aniPh0cj-W0qd49tnR_hQg1-yKhgmnmFcGAykIeeIbrSqTKPf7_lgGIfFECjruztC-Kbnh5aVpohjSVlmjnS2Rxj6Pg3SBTYEg1VU5shgPd3Cv_1OHYPpoI4vWodDRlv7vTDOIMIb3TxaYKrVY4kPk10lQJc_vZkVwq8pOdXci3VquKdkvX1P5iu6m8Iq0VPw5CJ6K1PUnrzuiedxKevbS3kzJjnXtEpxSVtbLMx5iXL7E_reeJMC8Q5bdg4qoSp94AIONwmrRWZapqZxhi5gSiRpoepa-IXqWTzqb9UA",
      "expirationTime":1621225265956},
      "redirectEventId":null,
      "lastLoginAt":"1621221667086",
      "createdAt":"1621221667086",
      "multiFactor":{"enrolledFactors":[]}}